### ISSUE TITLE
Host the frontend so it comes from the server

### ISSUE THREAD

**Issue by cubed-guy** [acmpesuecc/flappio#4]
The frontend works properly only when it runs through VSCode live server.
Add code to the server with routes for the frontend pages.

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by NishanHolla** [comment]
can i be assigned this ?

**Comment by akdino** [comment]
can you please assign this to me

**Comment by NishanHolla** [comment]
I would still like to be assigned this ?

**Comment by akdino** [comment]
could i please get assigned

**Comment by cubed-guy** [comment]
@sid-nc Please report progress by 4:30

**Comment by ShaheedMirjanaik** [comment]
@cubed-guy could i please get assigned

**Comment by cubed-guy** [comment]
Issue has been resolved
